name: Test CI CD #имя
on: # какие события будут обрабатываться
  push:
    branches: [master]
jobs: #задания, которые будет выполнять GitHub
  test-and-coverage-package:
    runs-on: ubuntu-latest #какая операционная система будет использоваться
    env:
      COVERAGE_HTML_REPORT_PATH: /tmp/coverage_html_report
      PYTEST_REPORT_PATH: /tmp/pytest_report.html
    steps: # шаги
      - name: "Checkout repository" #имя
        uses: actions/checkout@v3
      - name: "Install python"
        uses: actions/setup-python@v4
        with: #указание версии питона
          python-version: '3.8'
          architecture: 'x64'
      - name: "Install project dependencies" #Установка зависимостей
        run: pip install -r requirements.txt
      - name: "Run tests and code coverage analysis"
        run: coverage run tests/test.py pytest --html=${{ env.PYTEST_REPORT_PATH }} --self-contained-html
      - name: "Generate code coverage html report"
        run: coverage html --directory ${{ env.COVERAGE_HTML_REPORT_PATH }}
      - name: "Archive pytest and coverage reports"
        uses: actions/upload-artifact@v3
        if: ${{!cancelled()}}
        with:
          name: "Test and coverage reports"
          path: |
            ${{ env.PYTEST_REPORT_PATH }}
            ${{ env.COVERAGE_HTML_REPORT_PATH }}

  publish-package-as-artifact:
    needs: ["test-and-coverage-package"]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Publish package as artifact"
        uses: actions/upload-artifact@v3
        with:
          name: "Built package"
          path: "src"